# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/python-poetry/poetry
    rev: 1.8.2
    hooks:
    -   id: poetry-check
        args: ["-C", "./pittfinder"]
    -   id: poetry-lock
        args: ["-C", "./pittfinder"]
    -   id: poetry-export
        args: ["-o", "./requirements.txt"]
    -   id: poetry-install
        args: ["-C", "./pittfinder"]
-   repo: local
    hooks:
    -   id: mypy-system
        name: mypy
        entry: poetry run mypy
        language: system
        files: \.py$
# -   repo: https://github.com/PyCQA/isort
#     rev: 5.13.2
#     hooks:
#     -   id: isort
-   repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
    -   id: black
-   repo: local
    hooks:
    -   id: pylint-system
        name: pylint
        entry: poetry run pylint
        language: system
        files: \.py$
